repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.0
  hooks:
    - id: nbqa-black
      args: ["--nbqa-shell"]
    - id: nbqa-pyupgrade
      args: ["--py37-plus"]
    - id: nbqa-isort
      args: ["--float-to-top"]
